[package]
name = "shortest_palindrome"
version = "0.1.0"
authors = ["vvdf <t42please@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
